# Life Table

Dieser Datensatz enthält Daten zu Sterblichkeitsraten bestimmter Altersgruppen. Sie könnten im Zusammenhang mit COVID-19 Stehen da hohe Sterblichkeit vermutlich auf schlechte Hygienebedingungen und ein schlechtes Gesundheitssystem schließen lassen.

https://population.un.org/wpp/Download/Standard/CSV/

## Bedeutung der Spalten

* mx: Central death rate, nmx, for the age interval (x, x+n)
* qx: Probability of dying (nqx), for an individual between age x and x+n
* px: Probability of surviving, (npx), for an individual of age x to age x+n
* lx: Number of survivors, (lx), at age (x) for 100000 births
* dx: Number of deaths, (ndx), between ages x and x+n
* Lx: Number of person-years lived, (nLx), between ages x and x+n
* Sx: Survival ratio (nSx) corresponding to proportion of the life table population in age group (x, x+n) who are alive n year later
* Tx: Person-years lived, (Tx), above age x
* ex: Expectation of life (ex) at age x, i.e., average number of years lived subsequent to age x by those reaching age x
* ax: Average number of years lived (nax) between ages x and x+n by those dying in the interval

In [1]:
import pandas as pd

df = pd.read_csv("./data/WPP2019_Life_Table_Medium.csv", dtype={'Time': 'string'})
df.head()

,LocID,Location,VarID,Variant,Time,MidPeriod,SexID,Sex,AgeGrp,AgeGrpStart,...,mx,qx,px,lx,dx,Lx,Sx,Tx,ex,ax
0,4,Afghanistan,2,Medium,1950-1955,1953,1,Male,0,0,...,0.363600,0.292374,0.707626,100000.000,29237.420,80410.928,0.661270,2793722.2,27.9372,0.330
1,4,Afghanistan,2,Medium,1950-1955,1953,2,Female,0,0,...,0.314301,0.260983,0.739017,100000.000,26098.303,83036.103,0.686446,2943386.4,29.4339,0.350
2,4,Afghanistan,2,Medium,1950-1955,1953,3,Total,0,0,...,0.338950,0.276986,0.723014,100000.000,27698.596,81718.936,0.673642,2861783.5,28.6178,0.340
3,4,Afghanistan,2,Medium,1950-1955,1953,1,Male,1-4,1,...,0.049542,0.175186,0.824814,70762.580,12396.579,250224.180,0.858630,2713311.3,38.3439,1.352
4,4,Afghanistan,2,Medium,1950-1955,1953,2,Female,1-4,1,...,0.051585,0.181616,0.818384,73901.697,13421.696,260186.930,0.854939,2860350.3,38.7048,1.361

In [4]:
df_filtered = df[(df['Time'] == '2015-2020') & (df['SexID'] == 3)]
df_filtered.head()

,LocID,Location,VarID,Variant,Time,MidPeriod,SexID,Sex,AgeGrp,AgeGrpStart,...,mx,qx,px,lx,dx,Lx,Sx,Tx,ex,ax
860,4,Afghanistan,2,Medium,2015-2020,2018,3,Total,0,0,...,0.053947,0.051706,0.948294,100000.000,5170.592,95846.224,0.942107,6427897.2,64.2790,0.196654
863,4,Afghanistan,2,Medium,2015-2020,2018,3,Total,1-4,1,...,0.004307,0.017042,0.982958,94829.408,1616.126,375207.100,0.985752,6332051.0,66.7731,1.456554
866,4,Afghanistan,2,Medium,2015-2020,2018,3,Total,5-9,5,...,0.001327,0.006612,0.993388,93213.282,616.314,464341.540,0.994534,5956843.9,63.9055,2.201314
869,4,Afghanistan,2,Medium,2015-2020,2018,3,Total,10-14,10,...,0.001043,0.005202,0.994798,92596.968,481.664,461803.540,0.993437,5492502.4,59.3162,2.547446
872,4,Afghanistan,2,Medium,2015-2020,2018,3,Total,15-19,15,...,0.001684,0.008388,0.991612,92115.305,772.677,458772.950,0.989884,5030698.8,54.6131,2.665806